#include "PrariedogApp.h"
#include "Moose.h"
#include "AppFactory.h"
#include "MooseSyntax.h"

InputParameters PrariedogApp::validParams()
{
  auto params = MooseApp::validParams();
  return params;
}

PrariedogApp::PrariedogApp(InputParameters parameters) :
    MooseApp(parameters)
{
  Moose::registerObjects(_factory);
  PrariedogApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  PrariedogApp::associateSyntax(_syntax, _action_factory);
}

PrariedogApp::~PrariedogApp()
{
}

// External entry point for dynamic application loading
extern "C" void PrariedogApp__registerApps() { PrariedogApp::registerApps(); }
void
PrariedogApp::registerApps()
{
  registerApp(PrariedogApp);
}

// External entry point for dynamic object registration
extern "C" void PrariedogApp__registerObjects(Factory & factory) { PrariedogApp::registerObjects(factory); }
void
PrariedogApp::registerObjects(Factory & factory)
{
}

// External entry point for dynamic syntax association
extern "C" void PrariedogApp__associateSyntax(Syntax & syntax, ActionFactory & action_factory) { PrariedogApp::associateSyntax(syntax, action_factory); }
void
PrariedogApp::associateSyntax(Syntax & /*syntax*/, ActionFactory & /*action_factory*/)
{
}
